function output_mesh = generateCylinder(zmin, zmax, thmax, r, baseCenter, scale)
  [theta_z_positions, connections] = distmesh2d(@drectangle, ...
    @huniform, ...
    min([zmax-zmin,thmax*r])/scale, ...
    [zmin,0;zmax,thmax*r], ...
    [zmin,0; zmax,0; zmin,thmax*r; zmax,thmax*r], ...
    [zmin,zmax,0,thmax*r]);
  
  positions = [baseCenter(1) + cos(theta_z_positions(:,2)/r) .* r, ...
               baseCenter(2) + sin(theta_z_positions(:,2)/r) .* r, ...
               theta_z_positions(:,1)];
  output_mesh = triangulation(connections, positions);
end