function output_mesh = generateCylinder(zmin, zmax, thmax, r, baseCenter, scale)
  [theta_z_positions, connections] = distmesh2d(@drectangle, ...
    @huniform, ...
    min([zmax-zmin,2*thmax])/scale, ...
    [zmin,0;zmax,2*thmax], ...
    [zmin,0; zmax,0; zmin,2*thmax; zmax,2*thmax], ...
    [zmin,zmax,0,2*thmax]);
  
  positions = [baseCenter(1) + cos(0.5*theta_z_positions(:,2)) .* r, ...
               baseCenter(2) + sin(0.5*theta_z_positions(:,2)) .* r, ...
               theta_z_positions(:,1)];
  output_mesh = triangulation(connections, positions);
end